#!/bin/bash

# This script starts two MySQL docker containers in a primary-replica setup
# which can be used for running the replica tests in localtests/ .
# Set the environment var TEST_MYSQL_IMAGE to change the docker image.
#
# Usage:
#   docker-gh-ost-replica-tests up [-t]     start the containers
#   docker-gh-ost-replica-tests down        remove the containers
#   docker-gh-ost-replica-tests run [-t]    run replica tests on the containers
#
# Flags:
#   -t      use a toxiproxy for replica connection to simulate dropped connections

set -euo pipefail

GH_OST_ROOT=$(git rev-parse --show-toplevel)
if [[ ":$PATH:" != *":$GH_OST_ROOT:"* ]]; then
    export PATH="${PATH}:${GH_OST_ROOT}/script"
fi

poll_mysql() {
    CTR=0
    cmd="gh-ost-test-mysql-$1"
    while ! $cmd -e "select 1;" >/dev/null 2>&1; do
        sleep 1
        CTR=$((CTR + 1))
        if [ $CTR -gt 30 ]; then
            echo " ❌ MySQL $1 failed to start"
            return 1
        fi
    done
    echo " ✔ MySQL $1 OK"
    return 0
}

mysql-source() {
    if [[ $TEST_MYSQL_IMAGE =~ "mysql:8.4" ]]; then
        gh-ost-test-mysql-master --ssl-mode=required "$@"
    else
        gh-ost-test-mysql-master "$@"
    fi
}

mysql-replica() {
    if [[ $TEST_MYSQL_IMAGE =~ "mysql:8.4" ]]; then
        gh-ost-test-mysql-replica --ssl-mode=required "$@"
    else
        gh-ost-test-mysql-replica "$@"
    fi
}

create_toxiproxy() {
    curl --fail -X POST http://localhost:8474/proxies \
        -H "Content-Type: application/json" \
        -d '{"name": "mysql_proxy",
            "listen": "0.0.0.0:23308",
            "upstream": "host.docker.internal:3308"}'
    echo

    curl --fail -X POST http://localhost:8474/proxies/mysql_proxy/toxics \
        -H "Content-Type: application/json" \
        -d '{"name": "limit_data_downstream",
            "type": "limit_data",
            "attributes": {"bytes": 1000000}}'
    echo
}

setup() {
    if [ "$toxiproxy" = true ]; then
      echo "Starting $TEST_MYSQL_IMAGE with toxiproxy..."
    else
      echo "Starting $TEST_MYSQL_IMAGE..."
    fi

    echo "Compose file: $COMPOSE_FILE"

    docker compose up --wait

    echo "Waiting for MySQL..."
    poll_mysql "master" || exit 1
    poll_mysql "replica" || exit 1

    if [ "$toxiproxy" = true ]; then
        echo "Creating toxiproxy..."
        create_toxiproxy
        echo "OK"
    fi
}

ps() {
  docker compose ps
}

teardown() {
    echo "Stopping and deleting containers..."
    docker compose down
}

compose_setup() {
    # export TEST_MYSQL_IMAGE so it's parsed in docker-compose.yml
    export TEST_MYSQL_IMAGE="${TEST_MYSQL_IMAGE:-mysql:8.0}"
    [[ "${2:-}" == "-t" ]] && toxiproxy=true || toxiproxy=false

    local compose_path="$GH_OST_ROOT/script"
    # COMPOSE_FILE env var is recognised by docker compose and can contain multiple files
    export COMPOSE_FILE="$compose_path/docker-compose.yml"
    if [ "$toxiproxy" = true ]; then
        COMPOSE_FILE="${COMPOSE_FILE}:$compose_path/docker-compose.toxiproxy.yml"
    fi

    local major_minor
    major_minor="$(echo "$TEST_MYSQL_IMAGE" | sed 's/:/-/' | cut -d. -f1-2)"
    export CONF_PATH="$compose_path/docker/$major_minor"
}

main() {
    compose_setup "$@"
    local cmd="$1"
    if [[ "$cmd" == "up" ]]; then
        setup
    elif [[ "$cmd" == "down" ]]; then
        teardown
    elif [[ "$cmd" == "ps" ]]; then
        ps
    elif [[ "$cmd" == "run" ]]; then
        shift 1
        "$GH_OST_ROOT/localtests/test.sh" -d "$@"
    fi
}

main "$@"
