#!/bin/bash
#
# This executes a command on the mysql-primary docker container created
# from localtests/docker-compose.yml. It's used by localtests/test.sh.

# use -h 127.0.0.1 to force TCP port check instead of a connection via unix socket
docker compose exec --no-tty -e MYSQL_PWD=opensesame mysql-primary mysql -h 127.0.0.1 "$@"
